//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DouaCosmeticShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Product()
        {
            this.Table_OrderProduct = new HashSet<Table_OrderProduct>();
        }
    
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public Nullable<int> P_Quantity { get; set; }
        public Nullable<double> P_Price { get; set; }
        public string P_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_OrderProduct> Table_OrderProduct { get; set; }
    }
}
