//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DouaCosmeticShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_OrderProduct
    {
        public int OP_ID { get; set; }
        public Nullable<int> OP_Quantity { get; set; }
        public Nullable<int> O_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
    
        public virtual Table_Order Table_Order { get; set; }
        public virtual Table_Product Table_Product { get; set; }
    }
}
