//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DouaCosmeticShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Order()
        {
            this.Table_OrderProduct = new HashSet<Table_OrderProduct>();
        }
    
        public int O_ID { get; set; }
        public Nullable<int> C_ID { get; set; }
        public Nullable<System.DateTime> O_Created_at { get; set; }
        public Nullable<bool> O_Status { get; set; }
    
        public virtual Table_Customer Table_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_OrderProduct> Table_OrderProduct { get; set; }
    }
}
