//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterTakipYönetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int Per_ID { get; set; }
        public string Per_Ad { get; set; }
        public string Per_Soyad { get; set; }
        public string Per_Sube { get; set; }
        public string Per_Eposta { get; set; }
        public string Per_Sifre { get; set; }
        public string Per_Rol { get; set; }
        public Nullable<bool> Per_Durum { get; set; }
        public Nullable<System.DateTime> Per_SonGirisTarihi { get; set; }
    }
}
