//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterTakipYönetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Zimmet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Zimmet()
        {
            this.Tbl_Ariza = new HashSet<Tbl_Ariza>();
        }
    
        public int Zim_ID { get; set; }
        public Nullable<int> Kullanan_ID { get; set; }
        public Nullable<int> Env_ID { get; set; }
        public Nullable<int> Zimmetleyen_ID { get; set; }
        public Nullable<System.DateTime> Zim_Tarih { get; set; }
        public Nullable<System.DateTime> Zim_IadeTarih { get; set; }
        public string Zim_Aciklama { get; set; }
        public Nullable<bool> Zim_Kayit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Ariza> Tbl_Ariza { get; set; }
        public virtual Tbl_Envanter Tbl_Envanter { get; set; }
        public virtual Tbl_Personel Tbl_Personel { get; set; }
        public virtual Tbl_Personel Tbl_Personel1 { get; set; }
    }
}
