//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterTakipYönetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Envanter
    {
        public int Env_ID { get; set; }
        public Nullable<int> EnvCins_ID { get; set; }
        public Nullable<int> EnvMarka_ID { get; set; }
        public string Env_Model { get; set; }
        public string Env_SeriNo { get; set; }
        public string Env_Durum { get; set; }
        public Nullable<bool> Env_Kayit { get; set; }
        public Nullable<System.DateTime> Env_Tarih { get; set; }
        public Nullable<int> Per_ID { get; set; }
        public Nullable<int> Sube_ID { get; set; }
    
        public virtual Tbl_P_EnvanterCinsi Tbl_P_EnvanterCinsi { get; set; }
        public virtual Tbl_P_EnvanterMarka Tbl_P_EnvanterMarka { get; set; }
        public virtual Tbl_P_Sube Tbl_P_Sube { get; set; }
        public virtual Tbl_Personel Tbl_Personel { get; set; }
    }
}
