//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterTakipYönetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Personel()
        {
            this.Tbl_Ariza = new HashSet<Tbl_Ariza>();
            this.Tbl_Duyuru = new HashSet<Tbl_Duyuru>();
            this.Tbl_Envanter = new HashSet<Tbl_Envanter>();
            this.Tbl_Servis = new HashSet<Tbl_Servis>();
            this.Tbl_Zimmet = new HashSet<Tbl_Zimmet>();
            this.Tbl_Zimmet1 = new HashSet<Tbl_Zimmet>();
        }
    
        public int Per_ID { get; set; }
        public string Per_Ad { get; set; }
        public string Per_Soyad { get; set; }
        public Nullable<int> Sube_ID { get; set; }
        public string Per_Eposta { get; set; }
        public string Per_Sifre { get; set; }
        public string Per_Rol { get; set; }
        public Nullable<System.DateTime> Per_SonGirisTarihi { get; set; }
        public Nullable<bool> Per_Kayit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Ariza> Tbl_Ariza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Duyuru> Tbl_Duyuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Envanter> Tbl_Envanter { get; set; }
        public virtual Tbl_P_Rol Tbl_P_Rol { get; set; }
        public virtual Tbl_P_Sube Tbl_P_Sube { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Servis> Tbl_Servis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Zimmet> Tbl_Zimmet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Zimmet> Tbl_Zimmet1 { get; set; }
    }
}
