//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterTakipYönetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Duyuru
    {
        public int D_ID { get; set; }
        public string D_Konu { get; set; }
        public string D_Icerik { get; set; }
        public Nullable<int> Per_ID { get; set; }
        public Nullable<bool> D_Kayit { get; set; }
    
        public virtual Tbl_Personel Tbl_Personel { get; set; }
    }
}
