//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterTakipYönetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_P_Firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_P_Firma()
        {
            this.Tbl_Servis = new HashSet<Tbl_Servis>();
        }
    
        public int FirmaID { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaAdres { get; set; }
        public string FirmaTelefon { get; set; }
        public Nullable<bool> FirmaKayit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Servis> Tbl_Servis { get; set; }
    }
}
