//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterTakipYönetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ariza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Ariza()
        {
            this.Tbl_Servis = new HashSet<Tbl_Servis>();
        }
    
        public int Arz_ID { get; set; }
        public string Arz_Bilgi { get; set; }
        public string Arz_Durum { get; set; }
        public Nullable<System.DateTime> Arz_Tarih { get; set; }
        public Nullable<int> Per_ID { get; set; }
        public Nullable<int> Zim_ID { get; set; }
        public Nullable<bool> Arz_Kayit { get; set; }
    
        public virtual Tbl_Personel Tbl_Personel { get; set; }
        public virtual Tbl_Zimmet Tbl_Zimmet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Servis> Tbl_Servis { get; set; }
    }
}
