//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzdilekBtServisTakipPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvanterTb
    {
        public int EnvanterID { get; set; }
        public string Sube { get; set; }
        public string Lokasyon { get; set; }
        public string EnvanterCinsi { get; set; }
        public string EnvanterMarka { get; set; }
        public string EnvanterModel { get; set; }
        public string EnvanterSeriNo { get; set; }
        public string EnvanterOzellik { get; set; }
    }
}
