//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzdilekBtServisTakipPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvanterCinsi
    {
        public int EnvanterCinsiID { get; set; }
        public string EnvanterCinsiAdi { get; set; }
    }
}
