//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzdilekBtServisTakipPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServisGelenTb
    {
        public int ServisID { get; set; }
        public int EnvanterID { get; set; }
        public string Sube { get; set; }
        public string Lokasyon { get; set; }
        public string ServisGelenCinsi { get; set; }
        public string ServisGelenMarka { get; set; }
        public string ServisGelenModel { get; set; }
        public string ServisGelenSeriNo { get; set; }
        public string ServisGelenOzellik { get; set; }
        public string GonderenKisi { get; set; }
        public string GonderildigiTarih { get; set; }
        public string GeldiginiBelirtenKisi { get; set; }
        public string GeldigiTarih { get; set; }
        public string EkAksesuar { get; set; }
        public string ArizaSebebi { get; set; }
        public string YapilanMudahale { get; set; }
        public string ServisFirma { get; set; }
    }
}
