//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzdilekBtServisTakipPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServisTb
    {
        public int ServisID { get; set; }
        public int EnvanterID { get; set; }
        public string Sube { get; set; }
        public string Lokasyon { get; set; }
        public string ServisCinsi { get; set; }
        public string ServisMarka { get; set; }
        public string ServisModel { get; set; }
        public string ServisSeriNo { get; set; }
        public string ServisOzellik { get; set; }
        public string GonderenKisi { get; set; }
        public string GonderildigiTarih { get; set; }
        public string EkAksesuar { get; set; }
        public string ArizaSebebi { get; set; }
        public string ServisDurumu { get; set; }
        public string ServisFirma { get; set; }
    }
}
